spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: {postgres_url}
  username: {postgres_username}
  password: {postgres_password}
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: test.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000
